# Generated by Django 5.1.4 on 2024-12-20 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memo",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="memo",
            name="updated_at",
        ),
    ]
