# Generated by Django 4.1 on 2024-11-02 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_updated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="updated",
            new_name="updated_at",
        ),
    ]
