# Generated by Django 4.1 on 2024-12-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_tag_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hook_text",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
